assembly_keywords = {
    'assembly': 'assembly'
    'ets': 'assembly',
    'ets assembly': 'assembly',
    'steel': 'ETS-Assembly',
    'steel assembly': 'ETS-Assembly',
    'outbox': 'Outbox-Assembly',
    'outbox assembly': 'Outbox-Assembly',
    'box assembly': 'Outbox-Assembly',
    'cardboard assembly': 'Outbox-Assembly',
    'abs': 'ABS-Assembly',
    'abs assembly': 'ABS-Assembly',
    'brake': 'ABS-Assembly',
    'brake assembly': 'ABS-Assembly',
    'brake system assembly': 'ABS-Assembly',
    'wirth': 'Wirth-Werkzeugbau',
    'wirth-werkzeugbau': 'Wirth-Werkzeugbau',
    'car assembly': 'Wirth-Werkzeugbau',
    'car engine assembly': 'Wirth-Werkzeugbau',
    'automotive assembly': 'Wirth-Werkzeugbau',
    'circuit': 'PCBA-Assembly',
    'circuit board': 'PCBA-Assembly',
    'circuit board assembly': 'PCBA-Assembly',
    'furniture': 'Zapf-umzüge',
    'furniture assembly': 'Zapf-umzüge',
    'kitchen': 'Zapf-umzüge',
    'kitchen assembly': 'Zapf-umzüge',
    'industrial': 'Reiner-Assembly',
    'industrial assembly': 'Reiner-Assembly',
    'supply chain assembly': 'Reiner-Assembly'
}